[package]
name = "scraper"
version = "0.1.0"
authors = ["Jason Miesionczek <atmospherian@gmail.com>"]
edition = "2018"

[dependencies]
web-view = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
